---
# tasks file for mongodb
  
- name: Install a gnupg
  apt:
    name: gnupg
    state: present
    update_cache: True

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present

- name: MongoDB - Add repository
  apt_repository:
    filename: '/etc/apt/sources.list.d/mongodb-org-3.2.list'
    repo: 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse'
    state: present
    update_cache: True

- name: Install MongoDB's packages
  apt:
    name:
        - mongodb-org="{{ mongodb_version }}"
        - mongodb-org-server="{{ mongodb_version }}"
        - mongodb-org-shell="{{ mongodb_version }}"
        - mongodb-org-mongos="{{ mongodb_version }}"
        - mongodb-org-tools="{{ mongodb_version }}"
    state: present

- name: Run mongod demon
  service:
    name: mongod
    state: started
    enabled: True